### ISSUE TITLE
successKeys for FETPAPI Store Protocol Handlers are always empty.

### ISSUE THREAD

**Issue by Hoosayin** [F2I-Consulting/fetpapi#13]
Hi Philippe! 

I have been trying to put Data Objects on the store using AbstractSession::putDataObjects() method. I am using FETPAPI Store Protocol Handlers and been writing objects in a blocking call. After doing some debugging, it is clear that the message is handled from the sendingQueue successfully, and data objects are being written to the store. However, the successKeys field always has the size 0. It's not a big problem, but I am unable to make a decision in the code if data objects are written successfully or not since successKeys are always empty.

Here's the state:

![Screenshot 2023-06-13 124137](https://github.com/F2I-Consulting/fetpapi/assets/47661256/21f99869-5456-46c1-889b-7cc782fe0dee)

Please, let me know if this is a problem, or am I missing something.

Regards.

**Comment by philippeVerney** [comment]
HI Hussain,

Depending on your server, I suspect it is a bug on server side since there is a similar known one (now fixed) on RDDMS side : https://community.opengroup.org/osdu/platform/domain-data-mgmt-services/reservoir/open-etp-server/-/issues/19
Please verify your server side version and confirm or not.

**Comment by Hoosayin** [comment]
Thanks Philippe! Yes, it must be a bug on server side because I cloned Open ETP Server 4 months ago. I guess, I should pull latest commits made to that repository.
